### ISSUE TITLE
Why do we call Liang "Minister"?

### ISSUE THREAD

**Issue by DavidYQY** [HexaThreadGardener/PanRust#1]
While it is ture that she **is** Zero weights' fabulous minister, none of us call each other like *vice president* or *former president* . Is the new name associated with *OctoGardener*..?

**Comment by yiwenlu66** [comment]
No, it is not ture. [lol]

**Comment by ZeroWeight** [comment]
I don't think this topic needs further discussion.
As the saying goes, `` Things are already clear enough''

**Comment by yiwenlu66** [comment]
interesting
